# .streamlit/secrets.toml
rawg_api_key = "22ac8176b2254ae3b9b83a7938595386"

# .streamlit/secrets.toml

[twitch]
client_id = "f4relrjtee5ev5i6obx30ourvpf9g8"
client_secret = "3byyu29ptdfzghj0u1fp9n7s7s2uf7"
